---

- name: .:(kafka):. server.properties template
  template:
    src: templates/server.properties.j2
    dest: /home/kafka/kafka/config/server.properties
    force: yes

- name: .:(kafka):. removing the extra "," in 'zookeeper.connect:",...'
  replace:
    path: /home/kafka/kafka/config/server.properties
    regexp: '^(zookeeper.connect=),(.*)$'
    replace: '\1\2'

- name: .:(kafka):. insuring that kafka.logs directory is owned by kafka
  file:
    path: '{{log_dir}}'
    owner: kafka
    group: kafka
    recurse: yes
    state: directory
    mode: '0755'

- name: .:(kafka):. insuring that kafka.logs directory is empty
  shell: rm -rf '{{log_dir}}'/*


- name: .:(kafka):. insuring that kafka service logs directory is valid
  file:
    path: '/var/log/kafka'
    owner: kafka
    group: kafka
    state: directory
    mode: '0755'

- name: .:(kafka):. creating the kafka.serive file
  copy:
    src: files/kafka.service
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: '644'

- name: .:(kafka):. enabling kafka
  systemd:
    name: kafka
    daemon_reload: yes
    enabled: yes

