---
# vars file for config
# cluster_setting:
# the default values are taken from Brain's cassandra node
cluster_name: cassandra-mx-test
cdc_total_space_in_mb: 1713
concurrent_compactors: 2
compaction_throughput_mb_per_sec: 20
endpoint_snitch: GossipingPropertyFileSnitch   
batch_size_warn_threshold_in_kb: 1024
batch_size_fail_threshold_in_kb: 1024
start_rpc: false


# node config
disable_swap: true
# not used

