---

- name: .:(RHEL):. removing abrt package
  yum:
    name: abrt
    state: absent


- name: .:(RHEL):. copying the yum repo for scylla to the remote
  copy:
    src: files/scylla.repo
    dest: /etc/yum.repos.d/scylla.repo
    owner: root
    group: root
    mode: '644'

  
- name: .:(RHEL):. installing the scylla
  yum:
    name: scylla
    state: installed

# - name: .:(RHEL):. runing Scylla_setup
#   shell: scylla_setup | cat
