---
# tasks file for install

- name: docker installation
  import_tasks: Docker/docker.yml
  when: "'Master' in group_names or 'Worker' in group_names"

- name: k8s installation
  import_tasks: Kubernets/kubernets.yml
  when: "'Master' in group_names or 'Worker' in group_names"
