---
# tasks file for install

- name: install byobu and ufw
  apt:
    pkg: 
    - byobu
    - ufw
    state: present
    update_cache: yes

- name: enable byobu
  shell: byobu-enable

- name: docker installation
  import_tasks: Docker/docker.yml
