---
# tasks file for install

- name: install byobu
  apt:
    pkg: byobu
    state: present
    update_cache: yes

- name: enable byobu
  shell: byobu-enable

- name: docker installation
  import_tasks: Docker/docker.yml
