---

- name: .:(zookeeper):. starting the nodes
  systemd:
    state: started
    name: zookeeper
  ignore_errors: yes

- name: .:(zookeeper):. ensuring that the zookeeper node is up and joined to others
  wait_for:
    timeout: 3


