---
- name: prerequisites setup
  hosts: all
  tasks:
  - import_role:
      name: prerequisites
    vars:
      allow_clean_up: allow_clean_up
      allow_firewall_config: allow_firewall_config

- name: installation
  hosts: Nodes
  tasks:
  - import_role:
      name: install
    when: allow_install=='true'
    vars:
      allow_systemd_downgrade: allow_systemd_downgrade

- name: configuration
  hosts: Nodes
  tasks:
  - import_role:
      name: config 
    when: allow_config=='true'

- name: starting the cluster(seed nodes)
  hosts: Seed_Nodes
  tasks:
  - import_role:
      name: run
    when: allow_run=='true'

- name: starting the cluster(rest of the nodes)
  hosts: Nodes, !Seed_Nodes
  serial: 1
  tasks:
  - import_role:
      name: run
    when: allow_run=='true'
