---

- name: copying the sysctl.conf to the remote
  copy:
    src: files/sysctl.conf
    dest: /etc/sysctl.conf
    force: yes
    owner: root
    group: root
    mode: '644'

- name: sysctl -p
  command: sysctl -p
