---

- name: generating the scylla_setup command
  template:
    src: templates/scylla_setup.j2
    dest: /scylla_setup.sh
    force: yes

- name: running the scylla_setup command
  shell: sh /scylla_setup.sh | cat > output.txt
