---
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
  when: disable_swap == true

- name: Disable swap
  command: swapoff -a
  when: disable_swap == true

- name: generating the scylla_setup command
  template:
    src: templates/scylla_setup.j2
    dest: /scylla_setup.sh
    force: yes
    mode: '0777'

- name: running the scylla_setup command
  shell: sh /scylla_setup.sh | cat > output.txt
