---

- name: Create filesystem on disk
  filesystem:
    fstype: '{{filesystem}}'
    dev: '{{disk}}'

- name: mounting the disk
  mount:
    path: '{{destination}}'
    src: '{{disk}}'
    fstype: '{{filesystem}}'
    state: mounted

- name: configuring the ownership
  file:
    path: '{{destination}}'
    state: directory

