---
# tasks file for config

- name: mongodb configuration
  import_tasks: mongo_config.yml


- name: replicaSet configuration
  import_tasks: replicaSet_config.yml
  when: ansible_default_ipv4.address in groups['Primary']
