---

- name: mongod.conf template
  template:
    src: templates/mongod_conf.j2
    dest: /etc/mongod.conf
    force: yes
    group: mongod
    owner: mongod

- name: enabling mongodb
  systemd:
    name: mongod
    enabled: yes
    daemon_reload: yes

