---
# tasks file for install
- name: cassandra installation playbook for RHEL-based systems
  import_tasks: rhel.yml
  when: ansible_facts['os_family']|lower == 'redhat'
  vars:
    allow_systemd_downgrade: allow_systemd_downgrade


- name: cassandra installation playbook for Debian-based systems
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: enabling cassandra
  systemd:
    name: cassandra
    daemon_reload: yes
    enabled: yes

