---
# tasks file for roles/prerequisites
- name: firewall configuration
  import_role:
    name: firewall
  when: allow_firewall_config=='true'

- name: removeing the footprints of previous cassandra
  import_role:
    name: clean_up
  when: allow_clean_up=='true'
  