---
# tasks file for run

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: starting the nodes
  systemd:
    state: restarted
    name: scylla_server
  ignore_errors: yes

- name: ensuring that the scylla node is up and joined to the cluster
  wait_for:
    port: 7199
    delay: 30
