---
- name: .:(Debian):. installing the firewall
  apt:
    name: ufw
    update_cache: yes
- name: .:(Debian):. ensuring the ssh connection is up
  ufw:
    rule: allow
    port: item
    proto: tcp
  with_items:
  - ansible_ssh_port

- name: .:(Debian):. enabling the firewall
  ufw:
    state: enabled

- name: .:(Debian):. Allow all access to node_exporter tcp port 9100
  ufw:
    rule: allow
    port: '9100'
    proto: tcp
  when: allow_node_exporter_install == true

- name: .:(Debian):. Allow all access to cassandra_exporter tcp port 8080
  ufw:
    rule: allow
    port: '8080'
    proto: tcp
  when: allow_cassandra_exporter_install == true

- name: .:(Debian):. allowing connection from other nodes
  ufw:
    rule: allow
    from_ip: item
    from_port: any
  with_inventory_hostnames:
    -all
