---
# tasks file for clean_up
- name: stoping the cassandra
  systemd:
    name: cassandra
    state: stopped
  ignore_errors: yes

- name: deleting the directories --> lib
  file:
    path: /var/lib/cassandra
    state: absent
- name: deleting the directories --> log
  file:
    path: /var/log/cassandra
    state: absent
- name: deleting the directories --> etc
  file:
    path: /etc/cassandra
    state: absent

- name: uninstalling the cassandra for RHEL-based systems
  import_tasks: rhel.yml
  when: ansible_facts['os_family']|lower == 'redhat'
- name: uninstalling the cassandra for Debian-based systems
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes





