---
# tasks file for run

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: starting the nodes
  systemd:
    state: started
    name: cassandra
  ignore_errors: yes

- name: ensuring that the cassandra node is up and joined to the cluster
  wait_for:
    port: 7199
    delay: 30