---
# tasks file for run
- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: starting the seed nodes
  when: ansible_default_ipv4.address in groups['Seed_Nodes']
  systemd:
    state: started
    name: cassandra
  ignore_errors: yes

- name: starting rest of the nodes
  when: ansible_default_ipv4.address not in groups['Seed_Nodes']
  systemd:
    state: started
    name: cassandra
  ignore_errors: yes 