---
# tasks file for run
- name: starting the cluster
  block:
  - name: systemctl daemon-reload
    systemd:
      daemon_reload: yes

  - name: starting the seed nodes
    when: ansible_default_ipv4.address in groups['Seed_Nodes'] and allow_run=='true'
    systemd:
      state: started
      name: cassandra
    ignore_errors: yes

  - name: starting rest of the nodes
    
    when: ansible_default_ipv4.address not in groups['Seed_Nodes'] and allow_run=='true'
    systemd:
      state: started
      name: cassandra
    ignore_errors: yes 
  when: allow_run=='true'