---
# tasks file for run

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: starting the nodes
  # when: ansible_default_ipv4.address in groups['Seed_Nodes']
  systemd:
    state: started
    name: cassandra
  ignore_errors: yes

# - name: starting the seed nodes
#   when: ansible_default_ipv4.address in groups['Seed_Nodes']
#   systemd:
#     state: started
#     name: cassandra
#   ignore_errors: yes

# - name: starting rest of the nodes
#   when: ansible_default_ipv4.address not in groups['Seed_Nodes']
#   systemd:
#     state: started
#     name: cassandra
#   ignore_errors: yes 

# - name: sleep for 120 seconds before starting the play for another nodes
#   wait_for:
#     timeout: 120
- name: Wait for port 7199 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 7199
    delay: 3