---
# tasks file for kubernets-install

- name: installation playbook for RHEL-based systems
  import_tasks: rhel.yml
  when: ansible_facts['os_family']|lower == 'rhel'

- name: installation playbook for Debian-based systems
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

