---
- name: prerequisites setup
  hosts: all
  tasks:
  - import_role:
      name: prerequisites
    vars:
      allow_clean_up: allow_clean_up
      allow_firewall_config: allow_firewall_config
- name: installation
  hosts: all
  tasks:
  - import_role:
      name: install
    vars:
      allow_install: allow_install
- name: configuration
  hosts: all
  tasks:
  - import_role:
      name: config 
- name: starting the cluster
  hosts: all
  serial: 1
  tasks:
  - import_role:
      name: run
    vars:
      allow_run: allow_run