---
- name: prerequisites setup
  hosts: Joining
  tasks:
  - import_role:
      name: prerequisites
    when: apply_prerequisites == 'true'

- name: installation
  hosts: Joining
  tasks:
  - import_role:
      name: install
    when: allow_install== 'true'

- name: configuration
  hosts: Joining
  tasks:
  - import_role:
      name: config 
    when: allow_config== 'true'

- name: starting the zookeeper nodes
  hosts: Joining
  serial: 1
  tasks:
  - import_role:
      name: run
    when: allow_run== 'true'
    vars:
      mode: 'zookeeper'

- name: starting the kafka nodes
  hosts: Joining
  serial: 1
  tasks:
  - import_role:
      name: run
    when: allow_run== 'true'
    vars:
      mode: 'kafka'

