---
- name: prerequisites setup
  hosts: broker
  tasks:
  - import_role:
      name: prerequisites
    vars:
      allow_proxy_config: allow_proxy_config
      allow_clean_up: allow_clean_up
      allow_firewall_config: allow_firewall_config

- name: installation
  hosts: all
  tasks:
  - import_role:
      name: install
    when: allow_install=='true'

- name: configuration
  hosts: all
  tasks:
  - import_role:
      name: config 
    when: allow_config=='true'

- name: starting the cluster
  hosts: all 
  tasks:
  - import_role:
      name: run
    when: allow_run=='true'
